/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/companion/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Companion Message */
        post: operations["send_companion_message_companion_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companion/interrupt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Interrupt Companion */
        post: operations["interrupt_companion_companion_interrupt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companion/session/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Companion Session */
        post: operations["reset_companion_session_companion_session_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companion/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Companion History */
        get: operations["get_companion_history_companion_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companion/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Companion State */
        get: operations["get_companion_state_companion_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companion/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Companion Activity */
        post: operations["register_companion_activity_companion_activity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/llm/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Llm Runtime Settings */
        get: operations["get_llm_runtime_settings_settings_llm_runtime_get"];
        /** Update Llm Runtime Settings */
        put: operations["update_llm_runtime_settings_settings_llm_runtime_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/llm/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Providers */
        get: operations["get_providers_settings_llm_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/llm/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Provider Config */
        post: operations["update_provider_config_settings_llm_providers__provider_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/llm/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Routes */
        get: operations["get_routes_settings_llm_routes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/llm/routes/{feature}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Route
         * @description Payload: { "provider_id": "...", "model": "...", "temperature": ..., "top_p": ..., "presence_penalty": ..., "frequency_penalty": ... }
         */
        post: operations["update_route_settings_llm_routes__feature__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/llm/params/{feature}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feature Params
         * @description Fetch all generation parameters for a specific feature, with dynamic soul-based adjustments
         */
        get: operations["get_feature_params_settings_llm_params__feature__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/llm/models/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description List available LLM models for frontend configuration
         */
        get: operations["list_models_settings_llm_models_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Memory */
        post: operations["add_memory_memory_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Memory */
        post: operations["search_memory_memory_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/search/hybrid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search Memory Hybrid */
        post: operations["search_memory_hybrid_memory_search_hybrid_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/context/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear Context */
        post: operations["clear_context_memory_context_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Memories */
        get: operations["get_all_memories_memory_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/inspiration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Inspiration */
        get: operations["get_inspiration_memory_inspiration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/inspection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect Memory */
        get: operations["inspect_memory_memory_inspection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/inspection/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect Processing Status */
        get: operations["inspect_processing_status_memory_inspection_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/inspection/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect Tables */
        get: operations["inspect_tables_memory_inspection_tables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/inspection/table/{table_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect Table */
        get: operations["inspect_table_memory_inspection_table__table_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/inspection/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inspect Query */
        post: operations["inspect_query_memory_inspection_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_runtime_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shutdown Runtime */
        post: operations["shutdown_runtime_runtime_shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Network Config */
        get: operations["get_network_config_runtime_network_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runtime Contracts */
        get: operations["list_runtime_contracts_runtime_contracts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runtime Capabilities */
        get: operations["list_runtime_capabilities_runtime_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime/capabilities/{capability}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Runtime Capability */
        get: operations["get_runtime_capability_runtime_capabilities__capability__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/voiceprint/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description List all voiceprint profiles.
         */
        get: operations["list_profiles_capabilities_voiceprint_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/voiceprint/toggle/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle Profile
         * @description Toggle a voiceprint profile's enabled status.
         */
        post: operations["toggle_profile_capabilities_voiceprint_toggle__name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/voiceprint/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Profile
         * @description Delete a voiceprint profile.
         */
        delete: operations["delete_profile_capabilities_voiceprint__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/voiceprint/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Voiceprint
         * @description Upload audio to register a new voiceprint.
         *     Proxies to STT Worker for embedding generation.
         */
        post: operations["upload_voiceprint_capabilities_voiceprint_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/vision/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Image */
        post: operations["analyze_image_capabilities_vision_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/vision/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load Vision Model */
        post: operations["load_vision_model_capabilities_vision_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/vision/unload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unload Vision Model */
        post: operations["unload_vision_model_capabilities_vision_unload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/character/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Character Config
         * @description Get the single active character config.
         */
        get: operations["get_character_config_settings_character_config_get"];
        put?: never;
        /**
         * Update Character Config
         * @description Update the single active character config.
         */
        post: operations["update_character_config_settings_character_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/character/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description List available avatar models.
         */
        get: operations["list_models_settings_character_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/stt/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_capabilities_stt_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/stt/models/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Models
         * @description Proxy: List available STT models
         */
        get: operations["get_models_capabilities_stt_models_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/stt/models/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Switch Model
         * @description Proxy: Switch STT Model (and persist in Main)
         */
        post: operations["switch_model_capabilities_stt_models_switch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/stt/audio/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audio Devices */
        get: operations["list_audio_devices_capabilities_stt_audio_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/stt/audio/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Audio Config */
        post: operations["update_audio_config_capabilities_stt_audio_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/stt/voiceprint/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Voiceprint Status */
        get: operations["get_voiceprint_status_capabilities_stt_voiceprint_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/stt/audio/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audio Status */
        get: operations["get_audio_status_capabilities_stt_audio_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/tts/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_capabilities_tts_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/tts/models/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_capabilities_tts_models_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/tts/models/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch Model */
        post: operations["switch_model_capabilities_tts_models_switch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/tts/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Voices */
        get: operations["list_voices_capabilities_tts_voices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities/tts/synthesize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synthesize */
        post: operations["synthesize_capabilities_tts_synthesize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics Endpoint
         * @description Prometheus metrics endpoint.
         *
         *     Returns all collected metrics in Prometheus text format.
         *     Access: Localhost only for security.
         */
        get: operations["metrics_endpoint_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics Health
         * @description Health check for metrics subsystem.
         */
        get: operations["metrics_health_metrics_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddMemoryRequest
         * @description Add Memory Request
         */
        AddMemoryRequest: {
            /** User Id */
            user_id?: string | null;
            /** Character Id */
            character_id?: string | null;
            /**
             * User Name
             * @default User
             */
            user_name: string;
            /**
             * Companion Name
             * @default AI
             */
            companion_name: string;
            /** Messages */
            messages: components["schemas"]["MessageModel"][];
        };
        /** AudioDeviceInfo */
        AudioDeviceInfo: {
            /** Index */
            index: number;
            /** Name */
            name: string;
            /** Channels */
            channels?: number | null;
            /** Host Api */
            host_api?: string | null;
        };
        /** AudioDeviceListResponse */
        AudioDeviceListResponse: {
            /** Devices */
            devices?: components["schemas"]["AudioDeviceInfo"][];
            /** Current */
            current?: string | null;
        };
        /** AudioStatusResponse */
        AudioStatusResponse: {
            /** Device Name */
            device_name?: string | null;
            /** Vad Aggressiveness */
            vad_aggressiveness?: number | null;
            /** Speech Start Threshold */
            speech_start_threshold: number;
            /** Speech End Threshold */
            speech_end_threshold: number;
            /** Min Speech Frames */
            min_speech_frames: number;
        } & {
            [key: string]: unknown;
        };
        /** Body_analyze_image_capabilities_vision_analyze_post */
        Body_analyze_image_capabilities_vision_analyze_post: {
            /** File */
            file?: string | null;
            /** Image Base64 */
            image_base64?: string | null;
            /**
             * Prompt
             * @default Describe this image.
             */
            prompt: string;
        };
        /** Body_upload_voiceprint_capabilities_voiceprint_upload_post */
        Body_upload_voiceprint_capabilities_voiceprint_upload_post: {
            /** File */
            file: string;
        };
        /** CharacterAvatarConfig */
        CharacterAvatarConfig: {
            /**
             * Type
             * @default live2d
             */
            type: string;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Modelurl
             * @default
             */
            modelUrl: string;
            /**
             * Cubismcoreurl
             * @default
             */
            cubismCoreUrl: string;
            /**
             * Rendererruntimeurl
             * @default
             */
            rendererRuntimeUrl: string;
            behavior?: components["schemas"]["Live2DBehaviorConfig"];
        };
        /** CharacterAvatarModel */
        CharacterAvatarModel: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Type */
            type: string;
            /** Thumbnail */
            thumbnail?: string | null;
            /** Availability */
            availability?: string | null;
        };
        /** CharacterConfig */
        CharacterConfig: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Displayname */
            displayName?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Systemprompt
             * @default
             */
            systemPrompt: string;
            avatar?: components["schemas"]["CharacterAvatarConfig"];
            voiceConfig?: components["schemas"]["CharacterVoiceConfig"];
            /**
             * Heartbeatenabled
             * @default true
             */
            heartbeatEnabled: boolean;
            /**
             * Proactivechatenabled
             * @default true
             */
            proactiveChatEnabled: boolean;
            /**
             * Soulevolutionenabled
             * @default true
             */
            soulEvolutionEnabled: boolean;
            /**
             * Proactivethresholdminutes
             * @default 15
             */
            proactiveThresholdMinutes: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** CharacterModelListResponse */
        CharacterModelListResponse: {
            /** Models */
            models: components["schemas"]["CharacterAvatarModel"][];
        };
        /** CharacterVoiceConfig */
        CharacterVoiceConfig: {
            /**
             * Service
             * @default driver.tts.edge
             */
            service: string;
            /**
             * Voiceid
             * @default
             */
            voiceId: string;
            /**
             * Rate
             * @default +0%
             */
            rate: string;
            /**
             * Pitch
             * @default +0Hz
             */
            pitch: string;
        };
        /** ClearContextRequest */
        ClearContextRequest: {
            /** User Id */
            user_id?: string | null;
            /** Character Id */
            character_id?: string | null;
        };
        /** CompanionControlRequest */
        CompanionControlRequest: {
            /**
             * Session Id
             * @default 1
             */
            session_id: number;
            /**
             * Generation
             * @default 1
             */
            generation: number;
            /** Client Id */
            client_id?: string | null;
            /** Turn Id */
            turn_id?: string | null;
            /** User Id */
            user_id?: string | null;
            /** Character Id */
            character_id?: string | null;
            /** User Name */
            user_name?: string | null;
        };
        /** CompanionHistoryMessage */
        CompanionHistoryMessage: {
            /** Id */
            id: string;
            /** Turn Id */
            turn_id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
            /** Content */
            content: string;
            /**
             * Reasoning
             * @default
             */
            reasoning: string;
            /** Created At */
            created_at: string;
        };
        /** CompanionHistoryResponse */
        CompanionHistoryResponse: {
            /** Session Id */
            session_id: number;
            /** Messages */
            messages: components["schemas"]["CompanionHistoryMessage"][];
        };
        /** CompanionMessageRequest */
        CompanionMessageRequest: {
            /** Text */
            text: string;
            /**
             * Session Id
             * @default 1
             */
            session_id: number;
            /**
             * Generation
             * @default 1
             */
            generation: number;
            /** Client Id */
            client_id?: string | null;
            /** Turn Id */
            turn_id?: string | null;
            /** User Id */
            user_id?: string | null;
            /** Character Id */
            character_id?: string | null;
            /** User Name */
            user_name?: string | null;
            /** Model */
            model?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InspectionQueryRequest */
        InspectionQueryRequest: {
            /** Query */
            query: string;
        };
        /** Live2DBehaviorConfig */
        Live2DBehaviorConfig: {
            /**
             * Idlemotiongroup
             * @default Idle
             */
            idleMotionGroup: string;
            /**
             * Tapmotiongroup
             * @default TapBody
             */
            tapMotionGroup: string;
            /**
             * Taphitarea
             * @default Body
             */
            tapHitArea: string;
            /**
             * Idlethresholdms
             * @default 15000
             */
            idleThresholdMs: number;
            /**
             * Fitscale
             * @default 0.6
             */
            fitScale: number;
            /**
             * Verticalpositionratio
             * @default 0.6
             */
            verticalPositionRatio: number;
            /**
             * Timescale
             * @default 0.8
             */
            timeScale: number;
            parameters?: components["schemas"]["Live2DParameterBindings"];
        };
        /** Live2DParameterBindings */
        Live2DParameterBindings: {
            /**
             * Eyeblinkleft
             * @default ParamEyeLOpen
             */
            eyeBlinkLeft: string;
            /**
             * Eyeblinkright
             * @default ParamEyeROpen
             */
            eyeBlinkRight: string;
            /**
             * Mouthopen
             * @default ParamMouthOpenY
             */
            mouthOpen: string;
            /**
             * Headpan
             * @default ParamAngleX
             */
            headPan: string;
            /**
             * Headtilt
             * @default ParamAngleY
             */
            headTilt: string;
            /**
             * Headroll
             * @default ParamAngleZ
             */
            headRoll: string;
            /**
             * Bodypan
             * @default ParamBodyAngleX
             */
            bodyPan: string;
        };
        /**
         * MessageModel
         * @description Strict Chat Message Model
         */
        MessageModel: {
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Timestamp */
            timestamp?: number | null;
            /** Name */
            name?: string | null;
        };
        /** OperationStatusResponse */
        OperationStatusResponse: {
            /** Status */
            status: string;
            /** Detail */
            detail?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** RuntimeCapabilitiesResponse */
        RuntimeCapabilitiesResponse: {
            /** Capabilities */
            capabilities: components["schemas"]["RuntimeCapabilitySnapshot"][];
        };
        /** RuntimeCapabilitySnapshot */
        RuntimeCapabilitySnapshot: {
            /** Capability */
            capability: string;
            /**
             * Contract Version
             * @default 1.0
             */
            contract_version: string;
            /** Runtime Id */
            runtime_id?: string | null;
            /** Supported Operations */
            supported_operations?: string[];
            /** Selected Provider */
            selected_provider?: string | null;
            /** Current Provider */
            current_provider?: string | null;
            /** Runtime Target */
            runtime_target: string;
            /** Worker Id */
            worker_id: string;
            /** Worker Online */
            worker_online: boolean;
            /** Control Base Url */
            control_base_url: string;
            /** Direct Base Url */
            direct_base_url?: string | null;
            /** Stream Url */
            stream_url?: string | null;
            /** Token */
            token?: string | null;
            /** Last Error */
            last_error?: string | null;
            /** Load Time Ms */
            load_time_ms?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "starting" | "ready" | "offline" | "unavailable" | "failed";
            /** Provider State */
            provider_state?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** RuntimeLlmSettings */
        RuntimeLlmSettings: {
            /** Providerid */
            providerId: string;
            /**
             * Apikey
             * @default
             */
            apiKey: string;
            /**
             * Baseurl
             * @default
             */
            baseUrl: string;
            /** Model */
            model: string;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
            /**
             * Topp
             * @default 1
             */
            topP: number;
            /**
             * Presencepenalty
             * @default 0
             */
            presencePenalty: number;
            /**
             * Frequencypenalty
             * @default 0
             */
            frequencyPenalty: number;
            /**
             * Thinkingenabled
             * @default false
             */
            thinkingEnabled: boolean;
            /**
             * Historylimit
             * @default 20
             */
            historyLimit: number;
            /**
             * Overflowstrategy
             * @default slide
             */
            overflowStrategy: string;
        };
        /**
         * SearchRequest
         * @description Search Memory Request
         */
        SearchRequest: {
            /** User Id */
            user_id?: string | null;
            /** Character Id */
            character_id?: string | null;
            /** Query */
            query: string;
            /**
             * Limit
             * @default 10
             */
            limit: number | null;
            /**
             * Empower Factor
             * @default 0.5
             */
            empower_factor: number | null;
        };
        /** SttModelInfo */
        SttModelInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Active
             * @default false
             */
            active: boolean;
            /** Download Status */
            download_status?: ("idle" | "downloading" | "completed" | "failed") | null;
        };
        /** SttModelListResponse */
        SttModelListResponse: {
            /** Current Model */
            current_model?: string | null;
            /** Active Model */
            active_model?: string | null;
            /** Engine Type */
            engine_type?: string | null;
            /** Engine */
            engine?: string | null;
            /**
             * Loading Status
             * @default idle
             */
            loading_status: string;
            /** Models */
            models?: components["schemas"]["SttModelInfo"][];
            /** Vad Status */
            vad_status?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** SttSwitchModelRequest */
        SttSwitchModelRequest: {
            /** Model Name */
            model_name: string;
        };
        /** TtsEngineInfo */
        TtsEngineInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Desc
             * @default
             */
            desc: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Type
             * @default provider
             */
            type: string;
            /** Config Schema */
            config_schema?: {
                [key: string]: unknown;
            };
        };
        /** TtsModelListResponse */
        TtsModelListResponse: {
            /** Active */
            active?: string | null;
            /** Engines */
            engines?: components["schemas"]["TtsEngineInfo"][];
        };
        /** TtsSwitchRequest */
        TtsSwitchRequest: {
            /** Driver Id */
            driver_id?: string | null;
            /** Model Name */
            model_name?: string | null;
        };
        /** TtsSynthesisRequest */
        TtsSynthesisRequest: {
            /** Text */
            text: string;
            /**
             * Voice
             * @default zh-CN-XiaoxiaoNeural
             */
            voice: string;
            /** Emotion */
            emotion?: string | null;
            /**
             * Engine
             * @default driver.tts.edge
             */
            engine: string;
            /**
             * Rate
             * @default +0%
             */
            rate: string;
            /**
             * Pitch
             * @default +0Hz
             */
            pitch: string;
        };
        /** TtsVoiceInfo */
        TtsVoiceInfo: {
            /** Name */
            name: string;
            /**
             * Gender
             * @default Unknown
             */
            gender: string;
        } & {
            [key: string]: unknown;
        };
        /** UnifiedAudioConfig */
        UnifiedAudioConfig: {
            /** Device Name */
            device_name?: string | null;
            /** Enable Voiceprint Filter */
            enable_voiceprint_filter?: boolean | null;
            /** Voiceprint Threshold */
            voiceprint_threshold?: number | null;
            /** Voiceprint Profile */
            voiceprint_profile?: string | null;
            /** Vad Aggressiveness */
            vad_aggressiveness?: number | null;
            /** Speech Start Threshold */
            speech_start_threshold?: number | null;
            /** Speech End Threshold */
            speech_end_threshold?: number | null;
            /** Min Speech Frames */
            min_speech_frames?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoiceprintStatusResponse */
        VoiceprintStatusResponse: {
            /** Enabled */
            enabled: boolean;
            /** Loaded */
            loaded: boolean;
            /** Threshold */
            threshold: number;
            /** Profile */
            profile?: string | null;
            /** Profile Loaded */
            profile_loaded: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    send_companion_message_companion_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanionMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interrupt_companion_companion_interrupt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanionControlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_companion_session_companion_session_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanionControlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_companion_history_companion_history_get: {
        parameters: {
            query?: {
                user_id?: string | null;
                character_id?: string | null;
                user_name?: string | null;
                session_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanionHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_companion_state_companion_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_companion_activity_companion_activity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_llm_runtime_settings_settings_llm_runtime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeLlmSettings"];
                };
            };
        };
    };
    update_llm_runtime_settings_settings_llm_runtime_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuntimeLlmSettings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeLlmSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_providers_settings_llm_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_provider_config_settings_llm_providers__provider_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_routes_settings_llm_routes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_route_settings_llm_routes__feature__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feature_params_settings_llm_params__feature__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_settings_llm_models_list_get: {
        parameters: {
            query?: {
                provider_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_memory_memory_add_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_memory_memory_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_memory_hybrid_memory_search_hybrid_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_context_memory_context_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClearContextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_memories_memory_all_get: {
        parameters: {
            query?: {
                character_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_inspiration_memory_inspiration_get: {
        parameters: {
            query?: {
                character_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_memory_memory_inspection_get: {
        parameters: {
            query?: {
                character_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_processing_status_memory_inspection_status_get: {
        parameters: {
            query?: {
                character_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_tables_memory_inspection_tables_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    inspect_table_memory_inspection_table__table_name__get: {
        parameters: {
            query?: {
                limit?: number;
                character_id?: string | null;
            };
            header?: never;
            path: {
                table_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_query_memory_inspection_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InspectionQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_runtime_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    shutdown_runtime_runtime_shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_network_config_runtime_network_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_runtime_contracts_runtime_contracts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_runtime_capabilities_runtime_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeCapabilitiesResponse"];
                };
            };
        };
    };
    get_runtime_capability_runtime_capabilities__capability__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                capability: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeCapabilitySnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_capabilities_voiceprint_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    toggle_profile_capabilities_voiceprint_toggle__name__post: {
        parameters: {
            query: {
                enabled: boolean;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_capabilities_voiceprint__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_voiceprint_capabilities_voiceprint_upload_post: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_voiceprint_capabilities_voiceprint_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_image_capabilities_vision_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_image_capabilities_vision_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_vision_model_capabilities_vision_load_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    unload_vision_model_capabilities_vision_unload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_character_config_settings_character_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterConfig"];
                };
            };
        };
    };
    update_character_config_settings_character_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_settings_character_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterModelListResponse"];
                };
            };
        };
    };
    health_capabilities_stt_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_models_capabilities_stt_models_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SttModelListResponse"];
                };
            };
        };
    };
    switch_model_capabilities_stt_models_switch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SttSwitchModelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audio_devices_capabilities_stt_audio_devices_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioDeviceListResponse"];
                };
            };
        };
    };
    update_audio_config_capabilities_stt_audio_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnifiedAudioConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_voiceprint_status_capabilities_stt_voiceprint_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceprintStatusResponse"];
                };
            };
        };
    };
    get_audio_status_capabilities_stt_audio_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioStatusResponse"];
                };
            };
        };
    };
    health_capabilities_tts_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_models_capabilities_tts_models_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TtsModelListResponse"];
                };
            };
        };
    };
    switch_model_capabilities_tts_models_switch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TtsSwitchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_voices_capabilities_tts_voices_get: {
        parameters: {
            query?: {
                engine?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TtsVoiceInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    synthesize_capabilities_tts_synthesize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TtsSynthesisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_endpoint_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    metrics_health_metrics_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
